site_name: Communication Engineering
site_url: https://communication-engineering

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  - overrides/mathjax-init.js 

plugins:
  - search 
  - tags:
     tags_file: tags.md
  #- blog
  - blog:
      categories: true  # Enable categories
      archive: true     # Enable archive


# To define what files to include in the navigation
nav:
   - Home: index.md
   - Programme: chapters/programme/index.md
   - Introduction to Communication Engineering: chapters/introduction_to_communication_engineering/lecture.md
   - Signals and Systems Background: chapters/signals_and_systems_background/lecture.md
   - Linear Modulations: chapters/linear_modulations/lecture.md
   - Noise in Modulations: chapters/noise_in_modulations/lecture.md
   - Signals Sampling: chapters/signals_sampling/lecture.md
   - Pulse Code Modulation: chapters/pulse_code_modulation/lecture.md
   - Baseband Digital Transmission: chapters/baseband_digital_transmission/lecture.md
   - Multiplexing Systems: chapters/multiplexing_systems/lecture.md
   - Digital Modulations: chapters/digital_modulations/lecture.md  
   - Exercises: chapters/exercises/analog_communication/filters_and_energy/lecture.md
   - Tags: tags.md
   - Blog:
      - blog/index.md
   - Projects: chapters/projects/projects.md 
#  - Slides: slides.md

theme:
  name: material
  font: 
    text: Libre Franklin
    code: Red Hat Mono
  logo: assets/gc_icon.svg
  favicon: assets/gc_icon.svg
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections 
    #- navigation.instant.preview
    #- navigation.tracking I
    #- navigation.tabs
    - navigation.top 
    - search.suggest
    - search.highlight
    #- search.share
  palette:
    - scheme: slate # Dark Mode
      #primary: green
      primary: custom
      accent: custom
      toggle:
        #icon: material/weather-sunny  Button for switch to light mode
        #name: Dark mode

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange 

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details



extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@TheAmmiraglio625
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dr-gabriele-cavallaro/